### ISSUE TITLE
Unable to use to log in

### ISSUE THREAD

**Issue by safrench** [FreshSupaSulley/Auto-2FA#13]
Duo push never shows up in the extension, I keep getting this error message: (I tried resetting and setting it up again and it didn't help) 

"Failed to fetch @https://api-c03055b9.duosecurity.com/push/v2/device/transactions:

401 - Unauthorized
{\"code\":40102,\"message\":\"Invalid pkey in request credentials\",\"stat\":\"FAIL\"}"

**Comment by FreshSupaSulley** [comment]
Did you already have Duochrome setup, and then approving pushes stopped working? Or are you trying to set it up for the first time and didn't use it before

**Comment by safrench** [comment]
I haven't used it before, I hasn't worked since I first downloaded it

**Comment by FreshSupaSulley** [comment]
That's odd. We've had issues in the past where the API has had "downtimes" and then magically decides to work again after a random interval of time. Unsure if this is one of those times and you're just incredibly unlucky, or maybe your organization uses a specific Duo configuration that needs support (this was built to support Ohio State Univ). I'm not able to debug this until later today but I really appreciate you letting me know.

**Comment by safrench** [comment]
Thanks for helping! I'm at UC Irvine, I found this on my school's reddit so I'm pretty sure it's working for other people at my school

**Comment by FreshSupaSulley** [comment]
Was able to create a new device just now.

Go ahead and try it again. Weird how it doesn't work for you but for others at the same university. If you're tech-savvy, you could monitor the network traffic and paste the results here so I can get a better look at what might be happening.

**Comment by safrench** [comment]
It's working now! Thanks

**Comment by jach1337** [comment]
I'm also a UCI student, and I've been having the same issue. When initially setting up the extension, it works fine, but after a random interval - usually 1 to 2 days - the extension device gets removed.
![duo issue](https://github.com/user-attachments/assets/da8b7767-7019-4df6-b69e-d82de5177485)

**Comment by FreshSupaSulley** [comment]
Hi,
I originally thought this could relate to [this issue](https://github.com/FreshSupaSulley/Auto-2FA/issues/14) where there was a computer time synchronization problem, but your device... it's just gone. I've never seen that before.

Devices don't just get removed like that. This random 1-2 day interval before the device is **removed** (not just stops working) could suggest that this is human activity - where perhaps someone from your IT department is sifting through devices with non-traditional `model` information (it's attached at activation) and removing them from student's accounts. For instance, this extension's model property is "Auto 2Fa". Usually, this reads something like iPhone 13, or Google Pixel, etc. This makes it an easy target.

Can you elaborate on this 1-2 day interval? For instance, does the device always get deleted during business hours, or do you receive an email when this happens? I'd like to try renaming the model property to pretend to be an iPhone if you're willing to test it.

**Comment by jach1337** [comment]
Not sure of the exact time of day the device gets removed - I suspect it to be during business hours - but I don't receive any notification or email.

I do suspect it to be some manual action, as any devices that did use the Auto 2Fa extension were previously untouched; such devices only started to get removed in the aforementioned manner during the last 2 weeks.

**Comment by FreshSupaSulley** [comment]
Made a quick update to *just Firefox*, not Chrome yet. It now lies about the device information. When you activate Auto 2FA again, it should claim it's an iOS iPhone 13 instead of admitting it's an extension. Go ahead and manually update it, and please let me know if it gets deleted again or not.

**Comment by FreshSupaSulley** [comment]
Browsed through the UCI reddit - found a [post](https://www.reddit.com/r/UCI/comments/1ew7o9a/how_to_add_duo_verification_to_chrome/) where a student claimed that their Auto 2FA device was deleted thanks to their IT department.

I'm guessing the only way UCI would know it's not a supported device is by looking at the device information created at activation that says it's an extension (and not an iPhone, for instance). The solution is to randomly pick a device and platform (or just stick to a tablet) so they can't be confident it's an extension anymore. I could be wrong: they might have a better way to ensure it's an extension so still keep me updated, but due to this new information I'll be making a new update that adds this behavior.

Thanks for bringing this to my attention

**Comment by FreshSupaSulley** [comment]
@jach1337 any update? Does the device still get deleted from your account? Device information after the new patch initializes itself as a random iOS / Android tablet, so if the IT department really does deletes devices, it shouldn't happen anymore.

**Comment by jach1337** [comment]
So far, the device hasn't been removed after a week, so I think it works.

**Comment by FreshSupaSulley** [comment]
Cool, I'll close the issue then. If it happens again let me know :)
