### ISSUE TITLE
Bad request timestamp - 401

### ISSUE THREAD

**Issue by GNemesis99** [FreshSupaSulley/Auto-2FA#14]
Hey there, I'm currently facing an issue when setting up a new user. After inserting the duo code and setting up the authenticator we receive the following error message:

Auto 2FA An error occured: "Failed to fetch @https://api-e3b07386.duosecurity.com/push/v2/device/transactions: 401 - Unauthorized {\"code\":40105,\"message\":\"Bad request timestamp\",\"stat\":\"FAIL\"}" Try resetting Auto 2FA in settings. If this persists, open an issue.

![Screenshot_3](https://github.com/user-attachments/assets/44b38ee1-178e-4450-ab68-0c760e66f9d7)

We tried multiple times doing a clean instalation, using a clean chrome profile but we keep getting the same error. Do we have any solutions for this?

Thanks in Advance

**Comment by FreshSupaSulley** [comment]
Hi,

Just tried it myself and got it to work, weird how this sometimes happens. This has been a recurring problem, I think there's some error with how this extension deals with putting time in the API requests.

Try again periodically, it should eventually fix itself like it has for others in the past. I'll take a look at the activation process. Let me know if you get it to work.

**Comment by GNemesis99** [comment]
Thanks for the quick response!
I'm going to try again in a clean Windows image see if it solves my issue. Thanks again

**Comment by FreshSupaSulley** [comment]
Think I have a fix, just pushed a change to the repo. Are you using chrome, and do you know how to load unpacked extensions? If so, would you be willing to test the chrome extension by pulling the repo and using the chrome folder as the extension directory?

**Comment by FreshSupaSulley** [comment]
Nevermind - just submitted a hotfix that should be approved within the next 24 hours. I'll let you know when the version is released

**Comment by FreshSupaSulley** [comment]
Hotfix is released. Try to add the device, curious if it'll work for you

**Comment by GNemesis99** [comment]
It just seems like the error message changed. I thought it had something to do with the user credentials so we cleaned it all up but to no avail. 

![Screenshot_4](https://github.com/user-attachments/assets/7a641ec0-007a-4802-bda0-c0570c4348cc)

**Comment by FreshSupaSulley** [comment]
(I also updated the error message screen)
I was looking in the wrong place and made a change to UTC time calculation for all other endpoints.

This activation endpoint doesn't require a timestamp to be attached to the header. Is your computer's system time synced?


According to https://help.duo.com/s/article/3600?language=en_US:
> This is typically caused by your system's time being out of sync. Duo uses the timestamp as sent in the request by the system where Duo Authentication for Windows is installed to ensure the integrity of the authentication process.

**Comment by GNemesis99** [comment]
Wow I can't believe that that was it haha. Me and my team were trying multiple solutions and configurations to solve this issue and nothing seemed to work. Hard to believe that it was something simple like the computer's clock. Thank you for your support!
